import { BasicOrgChartTest } from "./stdFlowTest";
import { HierarchyTest } from "./hierarchyTest";
import { PerformanceTest } from "./performanceTest";
import { RevocationTest } from "./revocationTest";
import { SelfSignTest } from "./selfsignTest";
import { StrictRuleTest } from "./strictRuleTest";
import { RelRuleTest } from "./relRuleTest";
import { DisRuleTest } from "./disjRuleTest";
import { DemoLarge } from "./demoLargeTest";
import { DemoSmall } from "./demoSmallTest";

BasicOrgChartTest("BasicOrgChart");
BasicOrgChartTest("DynBasicOrgChart");
DisRuleTest("DisRuleOrgChart");
DisRuleTest("DynDisRuleOrgChart");
DemoLarge("DemoLargeOrgChart");
DemoLarge("DynDemoLargeOrgChart");
DemoSmall("DemoSmallOrgChart");
DemoSmall("DynDemoSmallOrgChart");
HierarchyTest("HierarchyOrgChart");
HierarchyTest("DynHierarchyOrgChart");
PerformanceTest("LargeOrgChart");
PerformanceTest("DynLargeOrgChart");
RelRuleTest("RelRuleOrgChart");
RelRuleTest("DynRelRuleOrgChart");
RevocationTest("RevocationOrgChart");
RevocationTest("DynRevocationOrgChart");
SelfSignTest("SelfSignOrgChart");
SelfSignTest("DynSelfSignOrgChart");
StrictRuleTest("StrictRuleOrgChart");
StrictRuleTest("DynStrictRuleOrgChart");
